services:
  devel:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/workspace
  devel-intel:
    environment:
      - USE_IPEX=true
    devices:
      - /dev/dri:/dev/dri
    image: intel/intel-extension-for-pytorch:latest
    shm_size: '4gb'
    privileged: true
    volumes:
      - .:/workspace
