services:
  devel:
    image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - .:/workspace
    shm_size: '16gb'
    network_mode: 'host'
  devel-intel:
    environment:
      - USE_IPEX=true
    devices:
      - /dev/dri:/dev/dri
    image: "intel/intel-extension-for-pytorch:2.1.20-xpu"
    shm_size: '16gb'
    volumes:
      - .:/workspace
